version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - app-network
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - ./mongo-data:/data/db

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_SERVICE_PORT=8080
      - JWT_SECRET=aHR0cHM6Ly93d3cueW91YmlsdW1hbWVyaWNhLmNvbS9sb2dpbi8=
    restart: always

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    networks:
      - app-network
    depends_on:
      - mongodb
      - gateway-service
    environment:
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/healthcare?authSource=admin
      - JWT_SECRET=aHR0cHM6Ly93d3cueW91YmlsdW1hbWVyaWNhLmNvbS9sb2dpbi8=
    restart: always

  doctor-service:
    build:
      context: ./doctor-service
    container_name: doctor-service
    networks:
      - app-network
    depends_on:
      - mongodb
      - gateway-service
    environment:
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/healthcare?authSource=admin
    restart: always

  patient-service:
    build:
      context: ./patient-service
    container_name: patient-service
    networks:
      - app-network
    depends_on:
      - mongodb
      - gateway-service
    environment:
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/healthcare?authSource=admin
    restart: always

  appointment-service:
    build:
      context: ./appointment-service
    container_name: appointment-service
    networks:
      - app-network
    depends_on:
      - mongodb
      - gateway-service
      - doctor-service
      - patient-service
      - kafka
    environment:
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/healthcare?authSource=admin
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_TOPIC=appointments
    restart: always

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    networks:
      - app-network
    depends_on:
      - mongodb
      - gateway-service
      - doctor-service
      - patient-service
      - appointment-service
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_GROUP_ID=appointment-notifications-group
      - KAFKA_TOPIC=appointments
      - MAIL_SERVER_HOST=smtp.gmail.com
      - MAIL_SERVER_PORT=587
      - MAIL_SERVER_USERNAME=noreplyhungrycoders@gmail.com
      - MAIL_SERVER_PASSWORD=password
    restart: always

  # ----------------------- FIXED KAFKA ----------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    networks:
      - app-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    networks:
      - app-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # ---------------------------------------------------------------

  ui-service:
    build:
      context: ./ui-component
    container_name: ui-service
    networks:
      - app-network
    depends_on:
      - mongodb
      - gateway-service
    ports:
      - "9090:80"
    restart: always

  admin-service:
    build:
      context: ./admin-service
    container_name: admin-service
    networks:
      - app-network
    depends_on:
      - appointment-service
      - auth-service
      - doctor-service
      - gateway-service
      - notification-service
      - patient-service
    ports:
      - "9093:8080"
    restart: always

networks:
  app-network:

volumes:
  mongo-data:
    driver: local
